[package]
name = "synthesize"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.79"
tempfile = "3.3.0"
bootspec = { path = "../bootspec" }

[dev-dependencies]
